### ISSUE TITLE
Make "Submit" more explicit (or auto-save) 

### ISSUE THREAD

**Issue by tiagovignatti** [Igalia/team#116]
I found it not easy to find the "Submit" button and was close to lose all the data that I have entered by almost closing the browser tab.

One idea to mitigate this problem is making the "Submit" button bigger and more easy to find in the UI. Alternatively maybe create an auto-save logic. 

My 2 cents only. Thanks for the work.

**Comment by alex-voodoo** [comment]
Auto-save would be maybe too much, but I think two things can improve the UX:
1. Add a Submit button under each category
2. Implement the logic that prevents closing the tab if there is unsaved data (and maybe mark the items that were changed)

**Comment by alex-voodoo** [comment]
I think the two UX fixes above solve the issue.  Feel free to reopen if you have better ideas.
