### ISSUE TITLE
Cannot create a project for another team

### ISSUE THREAD

**Issue by romulocintra** [Igalia/team#54]
Hi, every time I try to create a new project, app assumes this is for the team I work for instead of using the selected team in the select box

**Comment by alex-voodoo** [comment]
That is expected.  Projects in the skills application are designed to describe which skills are necessary for them, so they are "owned" by the team, and can only be edited by members of that team.

At the same time, the person can be assigned to multiple teams, which would make it possible for that person to edit projects assigned to any team they are in.
