### ISSUE TITLE
The import scripts should raise an alarm if an existing person was not found at the data source

### ISSUE THREAD

**Issue by catamorphism** [Igalia/team#83]
[Edited text to remove confidential info]

When filling out my team's interests vs. skills inventory, I noticed a person who left the company was included in our team. This is surprising to me since as far as I know, they were never on the team. Perhaps more importantly, they left the company a few months ago. Maybe there's a bug where people aren't removed from the database when they resign? Or is it on purpose in case people are rehired later?

**Comment by alex-voodoo** [comment]
This is not on purpose, just the removal is not yet implemented.

We currently have the primary data source of people… well, _elsewhere_, and the import script in the tool is non-destructive, it merges changes from that source but never deletes anything.

We have to remove ex-colleagues manually at this time.

**Comment by alex-voodoo** [comment]
I think that 1) the automation (e. g., import scripts) should not delete people from the DB, but 2) it should notify the system administrator that some person was not found at the source of the import.

Renaming the issue and updating the labels accordingly.
